workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
      xcode: latest
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter clean
          flutter pub get
      - name: Build iOS Unsigned
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release -derivedDataPath build/ios -arch arm64 CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
      - name: Create IPA
        script: |
          mkdir -p Payload
          cp -r build/ios/Release-iphoneos/Runner.app Payload/
          zip -r isopro.ipa Payload
    artifacts:
      - isopro.ipa
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
