workflows:
  ios-workflow:
    name: iOS Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      ios_signing:
        provisioning_profiles:
          - name: default
      vars:
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_ID: io.codemagic.isopro
    triggering:
      events:
        - push
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - user@example.com
        notify:
          success: true
          failure: false
